spring:
  datasource:
    username: admin
    password: rakeshjalsa
    url: jdbc:mysql://database-1.cneoakygun3g.ap-south-1.rds.amazonaws.com/sbms
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
